#!/bin/sh
# Auto-generated by ship-package.sh on 2026-06-10T00:12:28Z.
# Builds every Docker image packaged here. The --build-arg trio
# (DOCKER_USER / DOCKER_UID / DOCKER_GID) makes the in-container
# adduser/addgroup match the host running this script.

set -eu

scriptdir=`dirname "$0"`
scriptdir=`cd "$scriptdir" && pwd`
cd "$scriptdir"

D_USER=`whoami`
D_UID=`id -u`
D_GID=`id -g`

echo '>>> building dockergen/peqc-mlir-2025-llvm21'
docker build \
    --build-arg DOCKER_USER="$D_USER" \
    --build-arg DOCKER_UID="$D_UID" \
    --build-arg DOCKER_GID="$D_GID" \
    -f peqc-mlir-2025-llvm21.Dockerfile \
    -t dockergen/peqc-mlir-2025-llvm21 \
    .

